[features]
seeds = false
[programs.localnet]
social = "7p8C6xyHkFbexknPCjm1KbGmVgd1mbP4GRPKt7q9HLbn"

[programs.devnet]
social = "7p8C6xyHkFbexknPCjm1KbGmVgd1mbP4GRPKt7q9HLbn"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/anant/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
